# ----------------------
# RESTRICCIONES Y CONFIGURACIÓN GLOBAL
# ----------------------

# 🚫 Canales bloqueados (no permitidos para búsqueda o descarga)
CHANNEL_BLACKLIST = [
    '3huntleo',
    'God of Coffe'
    'Adam Conover',
    'Al Jokes',
    'Alpharad',
    'AnzuTops 365',
    'Anzutops777',
    'Asmongold',
    'Auron',
    'AuronPlay',
    'BackGuy',
    'BaityBait',
    'Batakotoons',
    'Beluga',
    'Bismuth',
    'Blue Jay',
    'Brendan Miller',
    'Casually Explained',
    'Casi Creativo',
    'charnew',
    'Chilaclips Esquizitos',
    'CircleToonsHD',
    'Casual Geographic', 
    'zerohuntleo'
    'Code Bullet',
    'Cookie',
    'Curious archive',
    'David Achu',
    'Diary of a CEO',
    'Dibrah',
    'Doobus Goobus',
    'Dragoon',
    'Dross',
    'Drossrank',
    'El mundo de zowl',
    'El plech',
    'El Rubius',
    'El ultimo TV nauta',
    'EmpLemon',
    'Enchufe TV',
    'Factorio',
    'Fernanfloo',
    'Fitnico',
    'Frozen prime',
    'Fzst',
    'Gonzok',
    'Gothamchess',
    'Generic Entertainment',
    'Greg Doucette',
    'Half as interesting',
    'HamonBeat',
    'Haroo',
    'I did a thing',
    'JackScepticEye',
    'Jaiden animations',
    'Javienator3000',
    'Jesse James West',
    'Joseju',
    'Julio Di Esto',
    'JuegaGerman',
    'Language Simp',
    'LALITO RAMS',
    'Lessons in Meme Culture',
    'Living Deadman',
    'Luetin',
    'Ludwig',
    'Lul Yeah',
    'Majorkill',
    'Man Carrying Thing'
    'ManlyBadassHero',
    'Markiplier',
    'Meat Cannyon',
    'MeatCanyon',
    'Memenade',
    'Miniminuteman',
    'Missasinfonia',
    'Mr Beast',
    'Nico Core',
    'Nostalfan',
    'OffendingEverybody',
    'Overly Sarcastic Prodductions',
    'Papa Meat',
    'PapaMeat',
    'penguinz0',
    'Pipepino',
    'Professor Lando',
    'QuickLag',
    'Ricky Tafolla',
    'Ricky tafollados',
    'Sam O Nella',
    'SCA entreteinment',
    'Solar Sands',
    'somethingelseyt',
    'Sr Pelo',
    'ssethtzeentach',
    'Summoning Salt',
    'Super Eye Patch Wolf',
    'T3rr0r',
    'Tale foundry',
    'Tech News Days',
    'The Duck Stories',
    'The game theorist',
    'Theorist',
    'Theory',
    'Tri Line',
    'Tu cosmopolis',
    'Vida Segun Richie',
    'Waffle Time',
    'Wefere',
    'Wesshamer',
    'WolfeyVGC',
    'X shift'
]


# 🚫 Palabras clave bloqueadas (filtra títulos o descripciones)
KEYWORD_BLACKLIST = [
    'Anime',
    'Bloons',
    'Bloons TD6',
    'challenge',
    'Comic',
    'Creppypasta',
    'Dandadan',
    'Dead Cells',
    'Death note',
    'Deltarune',
    'Dofus',
    'Dragon Ball',
    'Final fantasy',
    'fnf',
    'FNAF',
    'Franco Escamilla',
    'Friday Night Funkin',
    'Futurama',
    'Gachiakuta',
    'Gumball',
    'Hello Kitty',
    'Hollow Knight',
    'JoJo',
    'Kirby',
    'League of Legeneds',
    'lore',
    'Ludwig',
    'Magic the gathering',
    'Magi ',
    'Manga',
    'Marvel',
    'meme',
    'Minecraft',
    'Noita',
    'nuzlocke',
    'One Punch Man',
    'OPM',
    'Overlord',
    'Phineas',
    'Plants Vs Zombies',
    'Pokemon',
    'Pokemusu',
    'PvZ',
    'roguelike',
    'Silksong',
    'Sinbad',
    'Slice and Dice',
    'Smash',
    'Speedrun',
    'Spiderman',
    'Steel ball run',
    'Summoner',
    'syfr',
    'Terraria',
    'Tower Defense',
    'videogame',
    'Warhammer',
    'Yu Gi Oh',
]

