# ----------------------
# RESTRICCIONES Y CONFIGURACIÓN GLOBAL
# ----------------------

# 🚫 Canales bloqueados (no permitidos para búsqueda o descarga)
CHANNEL_BLACKLIST = [
    '3huntleo',
    'Adam Conover',
    'Al Jokes',
    'Alpharad',
    'AnzuTops 365',
    'Anzutops777',
    'Art Chad',
    'Asmongold',
    'Auron',
    'AuronPlay',
    'BackGuy',
    'BaityBait',
    'Batakotoons',
    'Beluga',
    'Bismuth',
    'Blue Jay',
    'Brendan Miller',
    'Casually Explained',
    'Casi Creativo',
    'charnew',
    'Chilaclips Esquizitos',
    'CircleToonsHD',
    'Code Bullet',
    'Cookie',
    'Curious archive',
    'Diary of a CEO',
    'Dibrah',
    'Doobus Goobus',
    'Dragoon',
    'Dross',
    'Drossrank',
    'El mundo de zowl',
    'El plech',
    'El Rubius',
    'El ultimo TV nauta',
    'EmpLemon',
    'Enchufe TV',
    'Factorio',
    'Fernanfloo',
    'Fitnico',
    'Frozen prime',
    'Fzst',
    'Gonzok',
    'Gothamchess',
    'Greg Doucette',
    'Half as interesting',
    'HamonBeat',
    'Haroo',
    'I did a thing',
    'JackScepticEye',
    'Jaiden animations',
    'Javienator3000',
    'Jeff Nippard',
    'Jesse James West',
    'Joseju',
    'Julio Di Esto',
    'JuegaGerman',
    'Language Simp',
    'LALITO RAMS',
    'Lessons in Meme Culture',
    'Living Deadman',
    'Luetin',
    'Ludwig',
    'Majorkill',
    'ManlyBadassHero',
    'Markiplier',
    'Meat Cannyon',
    'MeatCanyon',
    'Memenade',
    'Miniminuteman',
    'Missasinfonia',
    'Mr Beast',
    'Nico Core',
    'Nostalfan',
    'OffendingEverybody',
    'Overly Sarcastic Prodductions',
    'Papa Meat',
    'PapaMeat',
    'penguinz0',
    'Pipepino',
    'Professor Lando',
    'QuickLag',
    'Ricky Tafolla',
    'Ricky tafollados',
    'Sam O Nella',
    'SCA entreteinment',
    'Solar Sands',
    'somethingelseyt',
    'Sr Pelo',
    'ssethtzeentach',
    'Summoning Salt',
    'Super Eye Patch Wolf',
    'T3rr0r',
    'Tale foundry',
    'Tech News Days',
    'The Duck Stories',
    'The game theorist',
    'Theorist',
    'Theory',
    'Tri Line',
    'Tu cosmopolis',
    'Waffle Time',
    'Wefere',
    'Wesshamer',
    'WolfeyVGC',
    'X shift'
]


# 🚫 Palabras clave bloqueadas (filtra títulos o descripciones)
KEYWORD_BLACKLIST = [
    'Ai Slop',
    'Anime',
    'Bloons',
    'Bloons TD6',
    'challenge',
    'Comic',
    'Creppypasta',
    'Dandadan',
    'Dead Cells',
    'Dead Internet Theory',
    'Death note',
    'Defect',
    'Deltarune',
    'Dofus',
    'Dragon Ball',
    'FF',
    'Final fantasy',
    'fnf',
    'FNAF',
    'Franco Escamilla',
    'Friday Night Funkin',
    'Futurama',
    'Gachiakuta',
    'Gumball',
    'Hello Kitty',
    'Hollow Knight',
    'JoJo',
    'Kirby',
    'League of Legeneds',
    'look outside',
    'lore',
    'Ludwig',
    'Magic the gathering',
    'Magi ',
    'Manga',
    'Marvel',
    'meme',
    'Minecraft',
    'Mod',
    'News',
    'Noita',
    'nuzlocke',
    'One Punch Man',
    'OPM',
    'Overlord',
    'Phineas',
    'Plants Vs Zombies',
    'Pokemon',
    'Pokemusu',
    'PvZ',
    'purge',
    'roguelike',
    'Silksong',
    'Sinbad',
    'Slice and Dice',
    'Smash',
    'Speedrun',
    'Spiderman',
    'Steel ball run',
    'Summoner',
    'syfr',
    'TCG',
    'Terraria',
    'Tower Defense',
    'videogame',
    'Warhammer',
    'Yu Gi Oh',
]


# ⚙️ Límites de descargas diarias por tipo
DOWNLOAD_LIMITS = {
    "video": 2,
    "audio": 7,
    "playlist": 7
}

# 📅 Restricción de día 
def check_day_restriction():
    """Permite ejecutar el script solo los domingos."""
    from datetime import datetime
    today = datetime.now().weekday()  # 0 = lunes ... 6 = domingo
    if today == 5 or today == 6:
        return 
    else: 
        print("🚫 Las funciones de búsqueda y descarga solo están disponibles los domingos.")
        exit(0)
